// Free pool question bank — 44 questions (VR x25, Math x19)
export const FULL_FREE_POOL_QUESTIONS = [
  {
    id: "4af5c019-358e-43e2-b027-cb628ebd14f3",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.division",
    difficulty: "hard",
    prompt: "A school orders 15 boxes of exercise books. Each box contains 48 books. The books are shared equally among 9 classes. How many books does each class receive?",
    options: ["72","80","48","720"],
    correctAnswer: "80",
    renderType: "text",
    estTimeSeconds: 40,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["partial_calculation"],
    orderIndex: 761,
  },
  {
    id: "c5cb4fb6-cd23-4056-8b9e-c053ab603f8c",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "hard",
    prompt: "A cinema has 15 rows. The front 5 rows have 18 seats each. The middle 6 rows have 22 seats each, and the back 4 rows have 26 seats. For a showing, the front is 90% full, middle is 75% full, and back is 100% full. How many empty seats are there?",
    options: ["42","38","46","35"],
    correctAnswer: "42",
    renderType: "text",
    estTimeSeconds: 45,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["partial_calculation","wrong_subtraction"],
    orderIndex: 762,
  },
  {
    id: "473a6fef-a5a5-4429-a4b7-67c7831f504b",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "hard",
    prompt: "A car travels at 56 miles per hour. It drives for 3 hours and then for another 2 hours at 48 miles per hour. What is the total distance travelled?",
    options: ["280","264","96","168"],
    correctAnswer: "264",
    renderType: "text",
    estTimeSeconds: 40,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["partial_calculation"],
    orderIndex: 763,
  },
  {
    id: "44a685c5-a209-46f7-b23f-b8bdc8c887f1",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "hard",
    prompt: "A factory produces 1,250 widgets per day. It runs for 5 days a week. Defective widgets account for 38 per day. How many non-defective widgets are produced in a week?",
    options: ["6060","6088","6250","190"],
    correctAnswer: "6060",
    renderType: "text",
    estTimeSeconds: 45,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["partial_calculation","wrong_order"],
    orderIndex: 764,
  },
  {
    id: "0c299b35-6335-4e99-b5fe-c8d8fda4b9f9",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.subtraction",
    difficulty: "hard",
    prompt: "A charity event raises £2,450. The costs were £375 for the venue, £128 for food, and £97 for decorations. How much profit did the event make?",
    options: ["£600.00","£1850.00","£2450.00","£1947.00"],
    correctAnswer: "£1850.00",
    renderType: "text",
    estTimeSeconds: 40,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["partial_calculation"],
    orderIndex: 765,
  },
  {
    id: "d921a02b-2f91-4b69-a250-5df5bf6f29b7",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "hard",
    prompt: "A shop sells juice in packs of 6 bottles. Each bottle holds 330 ml. Mr Ahmed buys 4 packs. How many litres of juice does he buy?",
    options: ["2640","1320","7920","7.92"],
    correctAnswer: "7.92",
    renderType: "text",
    estTimeSeconds: 45,
    renderConfig: {},
    cognitiveLoad: 3,
    trapTypes: ["unit_conversion_error","partial_calculation"],
    orderIndex: 766,
  },
  {
    id: "fd8c1b95-0d13-480f-957f-b115306e49f6",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.addition",
    difficulty: "medium",
    prompt: "A baker makes 8 trays of rolls with 15 rolls per tray. He packs them into bags of 6. After filling as many bags as possible, how many rolls are left over?",
    options: ["0","2","4","3"],
    correctAnswer: "0",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation","wrong_operation"],
    orderIndex: 736,
  },
  {
    id: "21705c8b-d130-4ce0-b543-2ce9d942c742",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "medium",
    prompt: "A school trip costs £8 per pupil. 27 pupils go on the trip. The school also pays £45 for the coach. What is the total cost?",
    options: ["£261.00","£45.00","£216.00","£252.00"],
    correctAnswer: "£261.00",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 737,
  },
  {
    id: "e960b8db-bf70-4ac3-81e4-75fbb4560322",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "medium",
    prompt: "A gardener plants 15 rows of flowers with 8 flowers in each row. She then plants 23 more flowers along a path. How many flowers does she plant in total?",
    options: ["143","23","120","130"],
    correctAnswer: "143",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation","off_by_one"],
    orderIndex: 738,
  },
  {
    id: "f26ed3d3-1e81-4fc1-a176-ac37f80f4cb3",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "medium",
    prompt: "A school canteen serves 320 lunches per day. On Monday 15% of pupils were absent. On Tuesday 8% were absent. How many more lunches were served on Tuesday than Monday?",
    options: ["22","24","20","18"],
    correctAnswer: "22",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 739,
  },
  {
    id: "4b85534a-0265-4135-8f03-329d04a33e19",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.subtraction",
    difficulty: "medium",
    prompt: "The product of two consecutive odd numbers is 783. What is the sum of these two numbers?",
    options: ["56","58","54","60"],
    correctAnswer: "58",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation","wrong_operation"],
    orderIndex: 740,
  },
  {
    id: "476bc2bb-7d48-453f-8997-8ecb382a61e4",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.subtraction",
    difficulty: "medium",
    prompt: "A lorry carries 28 pallets. Each pallet has 4 layers of 15 boxes. If 12% of the boxes are damaged and cannot be delivered, how many boxes are actually delivered?",
    options: ["1,478","1,344","1,480","1,512"],
    correctAnswer: "1,478",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 741,
  },
  {
    id: "c29d7450-b82c-42dd-a04e-ca05daa0e28e",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.multiplication",
    difficulty: "medium",
    prompt: "A swimming pool is 25m long and 12m wide. Water is 1.4m deep throughout. If a pump removes 500 litres per minute, how many hours will it take to empty the pool? (1m³ = 1,000 litres)",
    options: ["14","12","16","10"],
    correctAnswer: "14",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 742,
  },
  {
    id: "361225e4-a208-4eb7-9d56-8437c169bc9f",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.division",
    difficulty: "medium",
    prompt: "There are 156 pupils in Year 5. 89 of them walk to school and the rest travel by bus. Each bus holds 15 pupils. How many buses are needed?",
    options: ["4","67","5","6"],
    correctAnswer: "5",
    renderType: "text",
    estTimeSeconds: 40,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["remainder_ignored","partial_calculation"],
    orderIndex: 743,
  },
  {
    id: "01fc6e03-6188-4ee1-9392-7bf85c6220be",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.division",
    difficulty: "medium",
    prompt: "A baker makes 144 cupcakes and puts them into boxes of 12. He sells 8 boxes. How many cupcakes does he have left?",
    options: ["12","36","96","48"],
    correctAnswer: "48",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 744,
  },
  {
    id: "fd32225d-a4ee-43b4-9190-fd24f572775e",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.bodmas",
    difficulty: "medium",
    prompt: "A shopkeeper charges £3 per item plus a £2 delivery fee. Tom buys 5 items. What is the total cost including delivery?",
    options: ["£17.00","£15.00","£25.00","£10.00"],
    correctAnswer: "£17.00",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["left_to_right_calculation"],
    orderIndex: 745,
  },
  {
    id: "79449b25-5f83-4afd-9e9b-ae73a9b4a5e6",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.bodmas",
    difficulty: "medium",
    prompt: "A school buys 15 packs of paper at £8.60 each and 8 boxes of pens at £12.75 each. They receive a £25 discount. What is the total cost?",
    options: ["£206.00","£206.50","£231.00","£256.00"],
    correctAnswer: "£206.00",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 746,
  },
  {
    id: "85b3bb4b-5e3e-4c72-9e9f-67f64ace728c",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.bodmas",
    difficulty: "medium",
    prompt: "A rectangle has a length of 12 cm and a width of 7 cm. A square with sides of 5 cm is cut from one corner. What is the remaining area?",
    options: ["25","84","59","109"],
    correctAnswer: "59",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation","wrong_operation"],
    orderIndex: 747,
  },
  {
    id: "ee52b78b-8f9d-4e9d-a865-7a258c299ecd",
    section: "Mathematics",
    skillId: "maths.arithmetic",
    subRuleId: "maths.arithmetic.bodmas",
    difficulty: "medium",
    prompt: "A parking garage charges £2.50 for the first hour and £1.80 for each additional hour. If a car is parked from 09:15 to 14:45, what is the total charge?",
    options: ["£11.50","£10.70","£12.30","£9.90"],
    correctAnswer: "£11.50",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 2,
    trapTypes: ["partial_calculation"],
    orderIndex: 748,
  },
  {
    id: "6e502037-443c-459d-8db0-c1c6f51aa5e1",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "easy",
    prompt: "In a code, HELP is coded as 6314, LEAP is coded as 1354. What is the code for HEEL?",
    options: ["6313","3631","6133","6331"],
    correctAnswer: "6331",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 0,
  },
  {
    id: "014bc2f9-2ac0-4884-b157-3a1bf3ca72b5",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "easy",
    prompt: "In a code, STAR is coded as 4219, RATS is coded as 9124. What is the code for TARS?",
    options: ["2149","9214","2914","2194"],
    correctAnswer: "2194",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 1,
  },
  {
    id: "c76b70c4-33da-47e8-a7a1-bb6aaa7a2f92",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "easy",
    prompt: "In a code, PLAN is coded as 8315, LAMP is coded as 3178. What is the code for PALM?",
    options: ["8173","8371","8317","8137"],
    correctAnswer: "8137",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 2,
  },
  {
    id: "e33b3976-5eb2-4bed-b8d9-744c5570ae50",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "easy",
    prompt: "In a code, SOIL is coded as 4623, OILS is coded as 6234. What is the code for SILO?",
    options: ["4263","4236","4632","4326"],
    correctAnswer: "4236",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 3,
  },
  {
    id: "f5ce6c16-9e3a-4eee-92b4-e1f1a31479d4",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "easy",
    prompt: "In a code, TEAM is coded as 2517, MATE is coded as 7125. What is the code for MEAT?",
    options: ["7521","7512","7152","7215"],
    correctAnswer: "7512",
    renderType: "text",
    estTimeSeconds: 30,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 4,
  },
  {
    id: "b0cfd818-8e8e-48bb-9147-29106ae9b776",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "easy",
    prompt: "In a code, CAT is written as FDW and DOG is written as GRJ. Using the same code, what is COG written as?",
    options: ["HTL","FRJ","GSK","EQI"],
    correctAnswer: "FRJ",
    renderType: "text",
    estTimeSeconds: 35,
    renderConfig: {},
    cognitiveLoad: 4,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 18,
  },
  {
    id: "1457d495-29e6-4eb3-9262-02ffb443350c",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "hard",
    prompt: "In a code, GRIN is coded as 2964, RING is coded as 9642. What is the code for GIRN?",
    options: ["2694","2496","2946","2649"],
    correctAnswer: "2694",
    renderType: "text",
    estTimeSeconds: 70,
    renderConfig: {},
    cognitiveLoad: 8,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 13,
  },
  {
    id: "e0c7c3ea-9c72-4fea-a3d9-6414ccd9ebae",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "hard",
    prompt: "In a code, MEAL is coded as 7513, LAME is coded as 3175, MALE is coded as 7135. What is the code for LEAM?",
    options: ["3517","3571","3751","3157"],
    correctAnswer: "3517",
    renderType: "text",
    estTimeSeconds: 70,
    renderConfig: {},
    cognitiveLoad: 8,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 14,
  },
  {
    id: "341c0dbe-d3cf-4092-bae6-7af5ae8ae7f9",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "hard",
    prompt: "In a code, WOLF is coded as 5639, FLOW is coded as 9365. What is the code for FOWL?",
    options: ["9653","9563","9356","9635"],
    correctAnswer: "9653",
    renderType: "text",
    estTimeSeconds: 70,
    renderConfig: {},
    cognitiveLoad: 8,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 15,
  },
  {
    id: "8cd0c802-74cc-4cfb-8f41-bc86aa6e97b3",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "hard",
    prompt: "In a code, PEAR is coded as 8519, REAP is coded as 9518. What is the code for PARE?",
    options: ["8159","8195","8915","8951"],
    correctAnswer: "8195",
    renderType: "text",
    estTimeSeconds: 70,
    renderConfig: {},
    cognitiveLoad: 8,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 16,
  },
  {
    id: "c8b1c95c-cb44-4cd4-8cc2-c56c01d8b685",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "hard",
    prompt: "In a code, SILK is coded as 4637, MILK is coded as 9637, SLIM is coded as 4369. What is the code for SKILL?",
    options: ["47633","43763","47363","47336"],
    correctAnswer: "47633",
    renderType: "text",
    estTimeSeconds: 70,
    renderConfig: {},
    cognitiveLoad: 8,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 17,
  },
  {
    id: "c8816d2d-2bb3-4254-8840-81bee0f2ca87",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "hard",
    prompt: "In a code, WATER is written as ZDWHU and LATER is written as ODWHU. Using the same code, what is SLATE written as?",
    options: ["UNCVG","WPEXI","XQFYJ","VODWH"],
    correctAnswer: "VODWH",
    renderType: "text",
    estTimeSeconds: 75,
    renderConfig: {},
    cognitiveLoad: 9,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 30,
  },
  {
    id: "739b9663-167e-4586-8b69-ddba4909c555",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, CARE is coded as 9163, RACE is coded as 6193. What is the code for ACRE?",
    options: ["1963","1936","1693","1639"],
    correctAnswer: "1963",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 5,
  },
  {
    id: "92b82305-b540-4b8b-ae57-23a858f7156b",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, TONE is coded as 2643, NOTE is coded as 4623. What is the code for TENT?",
    options: ["2342","2234","2324","2432"],
    correctAnswer: "2342",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 6,
  },
  {
    id: "5baec17e-56d6-455c-9b67-99402c821933",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, LIME is coded as 3675, MILE is coded as 7635. What is the code for ELIM?",
    options: ["5376","5736","5637","5367"],
    correctAnswer: "5367",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 7,
  },
  {
    id: "9791f917-2227-4097-a225-144a023f6dbf",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, SPOT is coded as 4862, TOPS is coded as 2684, POTS is coded as 8624. What is the code for STOP?",
    options: ["4286","4682","4628","4268"],
    correctAnswer: "4268",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 8,
  },
  {
    id: "41cd878b-1181-4664-a0b5-dd55208d25ce",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, ROPE is coded as 9685, PORE is coded as 8695. What is the code for REPO?",
    options: ["9658","9856","9586","9568"],
    correctAnswer: "9586",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 9,
  },
  {
    id: "fdd6b41e-85e7-4e1a-8a4a-6eacb7a9799a",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, LAKE is coded as 3175, KALE is coded as 7135. What is the code for LEAK?",
    options: ["3571","3751","3157","3517"],
    correctAnswer: "3517",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 10,
  },
  {
    id: "502918b7-9f77-471f-a908-ae85365a3c35",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, LIVE is coded as 3685, VEIL is coded as 8563, EVIL is coded as 5863. What is the code for VILE?",
    options: ["8653","8635","8365","8356"],
    correctAnswer: "8635",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 11,
  },
  {
    id: "9c994a0f-6f44-4aaa-92d5-e735ce1bb6c8",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.code_table",
    difficulty: "medium",
    prompt: "In a code, SNAP is coded as 4218, PANS is coded as 8124, NAPS is coded as 2184. What is the code for SPAN?",
    options: ["4812","4182","4821","4128"],
    correctAnswer: "4812",
    renderType: "text",
    estTimeSeconds: 50,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["letter_swap","partial_decode"],
    orderIndex: 12,
  },
  {
    id: "c1721eeb-f01c-4ccd-931f-b0a08fa410db",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "medium",
    prompt: "In a code, PEAK is written as SHDN and RAIN is written as UDLQ. Using the same code, what is PAIN written as?",
    options: ["UFNS","SDLQ","RCKP","TEMR"],
    correctAnswer: "SDLQ",
    renderType: "text",
    estTimeSeconds: 55,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 22,
  },
  {
    id: "40aac485-3cd5-4f33-b300-fc671da359fa",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "medium",
    prompt: "In a code, SHIP is written as VKLS and FISH is written as ILVK. Using the same code, what is FIST written as?",
    options: ["JMWX","ILVW","HKUV","KNXY"],
    correctAnswer: "ILVW",
    renderType: "text",
    estTimeSeconds: 55,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 23,
  },
  {
    id: "294ea36f-61d6-4da3-b183-01af277ef7c1",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "medium",
    prompt: "In a code, ROAD is written as URDG and LANE is written as ODQH. Using the same code, what is LOAD written as?",
    options: ["QTFI","NQCF","ORDG","PSEH"],
    correctAnswer: "ORDG",
    renderType: "text",
    estTimeSeconds: 55,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 24,
  },
  {
    id: "827909da-205f-40d9-ac03-307f52fd1346",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "medium",
    prompt: "In a code, HINT is written as JKPV and MINT is written as OKPV. Using the same code, what is MIST written as?",
    options: ["PLVW","OKUV","QMWX","NJTU"],
    correctAnswer: "OKUV",
    renderType: "text",
    estTimeSeconds: 55,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 25,
  },
  {
    id: "5b6e9ab6-8d59-4d52-923b-b3158aa73f16",
    section: "Verbal Reasoning",
    skillId: "vr.codes",
    subRuleId: "vr.codes.letter_shift",
    difficulty: "medium",
    prompt: "In a code, TIGER is written as UJHFS and LIONS is written as MJPOT. Using the same code, what is TILES written as?",
    options: ["WLOHV","TFJMU","VKNGU","UJMFT"],
    correctAnswer: "UJMFT",
    renderType: "text",
    estTimeSeconds: 55,
    renderConfig: {},
    cognitiveLoad: 6,
    trapTypes: ["wrong_shift","direction_error"],
    orderIndex: 26,
  },
] as const;
