import { GeneratedQuestion } from '../types';

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function makeQ(partial: Omit<GeneratedQuestion, 'section' | 'renderType' | 'renderConfig' | 'locale' | 'britishSpelling' | 'version'>): GeneratedQuestion {
  return {
    section: 'Verbal Reasoning',
    renderType: 'text',
    renderConfig: {},
    locale: 'en-GB',
    britishSpelling: true,
    version: 1,
    ...partial,
  };
}

function generateSentenceCompletionQuestions(): GeneratedQuestion[] {
  const items: { sentence: string; answer: string; distractors: string[]; diff: string; cog: number; time: number }[] = [
    { sentence: 'The sun ____ in the east every morning.', answer: 'rises', distractors: ['sets', 'falls', 'drops'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'Water ____ at 100 degrees Celsius.', answer: 'boils', distractors: ['freezes', 'melts', 'evaporates'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'Birds ____ south for the winter.', answer: 'migrate', distractors: ['hibernate', 'excavate', 'celebrate'], diff: 'easy', cog: 3, time: 25 },
    { sentence: 'A decade is a period of ____ years.', answer: 'ten', distractors: ['five', 'twenty', 'hundred'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'After autumn comes ____.', answer: 'winter', distractors: ['spring', 'summer', 'autumn'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'A ____ is someone who studies the stars and planets.', answer: 'astronomer', distractors: ['astrologer', 'astronaut', 'architect'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The soldiers showed great ____ in battle.', answer: 'courage', distractors: ['cowardice', 'caution', 'aggression'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The orchestra played a beautiful ____.', answer: 'symphony', distractors: ['sympathy', 'symptom', 'synonym'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'Evaporation is the process by which water turns into ____.', answer: 'vapour', distractors: ['ice', 'steam', 'mist'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The ____ of the novel kept readers guessing until the final page.', answer: 'suspense', distractors: ['substance', 'suspicion', 'sentiment'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The river ____ through the valley before reaching the sea.', answer: 'meanders', distractors: ['mediates', 'measures', 'moderates'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'A peninsula is a piece of land almost entirely surrounded by ____.', answer: 'water', distractors: ['mountains', 'desert', 'forest'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The scientist made a ____ discovery that changed modern medicine.', answer: 'groundbreaking', distractors: ['controversial', 'accidental', 'theoretical'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The politician spoke with great ____, convincing many voters.', answer: 'eloquence', distractors: ['elegance', 'arrogance', 'confidence'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The ____ between the two countries lasted for decades.', answer: 'alliance', distractors: ['rivalry', 'distance', 'boundary'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The ____ of the mountain was covered in snow.', answer: 'summit', distractors: ['surface', 'shadow', 'shelter'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'An ____ is a building where aircraft are kept.', answer: 'hangar', distractors: ['hanger', 'harbour', 'garage'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The children watched the ____ of butterflies in the garden.', answer: 'flutter', distractors: ['flock', 'flight', 'fumble'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The ____ landscape stretched for miles with no sign of life.', answer: 'barren', distractors: ['baron', 'beautiful', 'balanced'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'A ____ is a person who writes plays.', answer: 'playwright', distractors: ['playwrite', 'author', 'screenwriter'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The ____ of the ship guided it safely through the storm.', answer: 'captain', distractors: ['compass', 'current', 'cabin'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The museum contained many ____ artefacts from ancient Egypt.', answer: 'valuable', distractors: ['voluntary', 'variable', 'venerable'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The explorers felt a great sense of ____ when they reached the summit.', answer: 'achievement', distractors: ['attachment', 'amusement', 'agreement'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The ____ of the volcano caused widespread damage.', answer: 'eruption', distractors: ['erosion', 'evolution', 'emission'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The goalkeeper made a ____ save in the last minute.', answer: 'spectacular', distractors: ['speculative', 'spontaneous', 'superficial'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The children were ____ to open their presents on Christmas morning.', answer: 'eager', distractors: ['equal', 'early', 'eastern'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'A ____ is a large body of salt water.', answer: 'ocean', distractors: ['lake', 'river', 'pond'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The magician performed a ____ trick that amazed everyone.', answer: 'remarkable', distractors: ['removable', 'reliable', 'reasonable'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The ____ weather forced the event to be cancelled.', answer: 'severe', distractors: ['several', 'separate', 'serial'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The teacher asked the pupils to form a ____ line.', answer: 'straight', distractors: ['strange', 'strong', 'strict'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'A ____ is someone who studies the stars and planets.', answer: 'astronomer', distractors: ['astrologer', 'astronaut', 'architect'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The ancient castle was surrounded by a deep ____.', answer: 'moat', distractors: ['ditch', 'moan', 'coat'], diff: 'medium', cog: 3, time: 25 },
    { sentence: 'It is ____ to wear a seatbelt when travelling in a car.', answer: 'compulsory', distractors: ['competitive', 'comfortable', 'compatible'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The river ____ slowly through the valley.', answer: 'meandered', distractors: ['measured', 'mentioned', 'memorised'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The firefighters showed great ____ by entering the burning building.', answer: 'bravery', distractors: ['battery', 'bakery', 'brewery'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The ____ of the forest made it a perfect hiding place.', answer: 'density', distractors: ['beauty', 'silence', 'darkness'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'A ____ is a person who designs buildings.', answer: 'architect', distractors: ['archaeologist', 'artist', 'accountant'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The pupils were told to ____ their homework by Friday.', answer: 'complete', distractors: ['compete', 'compare', 'compose'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The ____ weather prevented the cricket match from taking place.', answer: 'inclement', distractors: ['incredible', 'inclusive', 'incorrect'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'She felt a sense of ____ after finishing the marathon.', answer: 'accomplishment', distractors: ['abandonment', 'acknowledgement', 'advertisement'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The postman delivers letters every day without ____.', answer: 'fail', distractors: ['fear', 'food', 'fuel'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The library was so ____ you could hear a pin drop.', answer: 'quiet', distractors: ['quick', 'quite', 'quaint'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The ship sailed across the ____ ocean.', answer: 'vast', distractors: ['fast', 'last', 'past'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The detective found a ____ clue at the crime scene.', answer: 'vital', distractors: ['visual', 'viral', 'virtual'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The old man had a ____ knowledge of local history.', answer: 'profound', distractors: ['prolonged', 'promoted', 'proposed'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The garden was full of ____ flowers in the spring.', answer: 'beautiful', distractors: ['bountiful', 'botanical', 'beneficial'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The train arrived ____ at the station.', answer: 'punctually', distractors: ['particularly', 'practically', 'previously'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The magician performed an ____ trick for the audience.', answer: 'astonishing', distractors: ['ascending', 'assembling', 'assessing'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The ____ cat sat by the fire all evening.', answer: 'contented', distractors: ['connected', 'converted', 'concerned'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'We need to ____ the broken fence before the sheep escape.', answer: 'repair', distractors: ['repeat', 'replace', 'remove'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The ____ of the river made it impossible to cross.', answer: 'depth', distractors: ['death', 'dealt', 'drift'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The children were ____ about the school trip.', answer: 'enthusiastic', distractors: ['endangered', 'enchanted', 'engineered'], diff: 'hard', cog: 6, time: 40 },
    { sentence: 'The bread was fresh from the ____.', answer: 'bakery', distractors: ['battery', 'balcony', 'bravery'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'Heavy rain caused ____ flooding in the village.', answer: 'severe', distractors: ['several', 'service', 'servant'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The explorer made a ____ discovery in the cave.', answer: 'remarkable', distractors: ['removable', 'renewable', 'regrettable'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The weather forecast predicted ____ skies for the weekend.', answer: 'clear', distractors: ['clean', 'close', 'climb'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The village was ____ after the storm passed.', answer: 'peaceful', distractors: ['powerful', 'plentiful', 'playful'], diff: 'medium', cog: 4, time: 30 },
    { sentence: 'The teacher asked the class to ____ their answers carefully.', answer: 'consider', distractors: ['consume', 'construct', 'conclude'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The knight wore a suit of ____ into battle.', answer: 'armour', distractors: ['armada', 'arsenal', 'arrival'], diff: 'easy', cog: 2, time: 20 },
    { sentence: 'The museum had an ____ collection of ancient pottery.', answer: 'impressive', distractors: ['impossible', 'impatient', 'important'], diff: 'medium', cog: 5, time: 35 },
    { sentence: 'The scientist made an ____ breakthrough in her research.', answer: 'extraordinary', distractors: ['extravagant', 'exhausting', 'experimental'], diff: 'hard', cog: 7, time: 45 },
    { sentence: 'The children built a ____ out of sand on the beach.', answer: 'castle', distractors: ['cradle', 'candle', 'cattle'], diff: 'easy', cog: 2, time: 20 },
  ];
  const questions: GeneratedQuestion[] = [];

  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.sentence,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.sentence_completion',
      trapTypes: ['semantic_distractor'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: `The correct word to complete the sentence is '${item.answer}'.`,
      qaStatus: 'approved',
      stemVariantId: `sentence_completion_${i}`,
      distractorStyleId: 'semantic_distractor',
    }));
  }
  return questions;
}

function generateLogicalDeductionQuestions(): GeneratedQuestion[] {
  const items: { premise: string; answer: string; distractors: string[]; diff: string; cog: number; time: number; explanation: string }[] = [
    { premise: 'All dogs are animals. Rex is a dog. Therefore, Rex is ____.',
      answer: 'an animal', distractors: ['a cat', 'a plant', 'a bird'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Since all dogs are animals and Rex is a dog, Rex must be an animal.' },
    { premise: 'Tom is taller than Sam. Sam is taller than Jack. Who is the shortest?',
      answer: 'Jack', distractors: ['Tom', 'Sam', 'They are equal'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Tom > Sam > Jack, so Jack is the shortest.' },
    { premise: 'All roses are flowers. Some flowers are red. Can we say all roses are red?',
      answer: 'No', distractors: ['Yes', 'Sometimes', 'Only in summer'], diff: 'easy', cog: 4, time: 30,
      explanation: 'We know all roses are flowers and some flowers are red, but we cannot conclude all roses are red.' },
    { premise: 'No fish can fly. A salmon is a fish. Can a salmon fly?',
      answer: 'No', distractors: ['Yes', 'Sometimes', 'Only at night'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Since no fish can fly and a salmon is a fish, a salmon cannot fly.' },
    { premise: 'If it rains, the ground gets wet. The ground is wet. Did it definitely rain?',
      answer: 'Not necessarily', distractors: ['Yes', 'No', 'Only if it is cold'], diff: 'medium', cog: 5, time: 35,
      explanation: 'The ground could be wet for other reasons (e.g. a hose), so rain is not the only explanation.' },
    { premise: 'All children in Class 5 wear a blue jumper. Sarah wears a blue jumper. Is Sarah definitely in Class 5?',
      answer: 'Not necessarily', distractors: ['Yes', 'No', 'Only on Mondays'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Other people may also wear blue jumpers, so we cannot be certain Sarah is in Class 5.' },
    { premise: 'Every pupil who finished the test received a sticker. James did not receive a sticker. What can we conclude?',
      answer: 'James did not finish the test', distractors: ['James finished the test', 'James lost his sticker', 'James was absent'], diff: 'medium', cog: 5, time: 35,
      explanation: 'If finishing the test means getting a sticker, and James has no sticker, he did not finish.' },
    { premise: 'If all Zogs are Bips, and all Bips are Cags, are all Zogs also Cags?',
      answer: 'Yes', distractors: ['No', 'Sometimes', 'Not enough information'], diff: 'medium', cog: 6, time: 40,
      explanation: 'All Zogs are Bips, and all Bips are Cags, so all Zogs must be Cags (transitive reasoning).' },
    { premise: 'Some teachers are musicians. All musicians practise daily. What can we say about some teachers?',
      answer: 'Some teachers practise daily', distractors: ['All teachers practise daily', 'No teachers practise daily', 'Teachers never practise'], diff: 'hard', cog: 7, time: 45,
      explanation: 'The teachers who are musicians must practise daily, so some teachers practise daily.' },
    { premise: 'If it is Saturday or Sunday, the library is closed. The library is open. What can we conclude?',
      answer: 'It is not Saturday or Sunday', distractors: ['It is Saturday', 'It is Sunday', 'The library is closed'], diff: 'hard', cog: 6, time: 40,
      explanation: 'Since the library is open, it cannot be Saturday or Sunday.' },
    { premise: 'All swans in this lake are white. Some birds in this lake are swans. What can we say about some birds?',
      answer: 'Some birds in this lake are white', distractors: ['All birds are white', 'No birds are white', 'All swans are birds'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Some birds are swans, and all swans here are white, so some birds must be white.' },
    { premise: 'Emma is older than Fiona. Fiona is older than Grace. Grace is older than Holly. Who is the oldest?',
      answer: 'Emma', distractors: ['Fiona', 'Grace', 'Holly'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Emma > Fiona > Grace > Holly, so Emma is the oldest.' },
    { premise: 'All squares are rectangles. All rectangles have four sides. A rhombus also has four sides. Is a rhombus a square?',
      answer: 'Not necessarily', distractors: ['Yes', 'No', 'Always'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Having four sides does not make something a rectangle or a square. A rhombus has four sides but is not necessarily a square.' },
    { premise: 'No child in the choir plays football. Jake plays football. Can Jake be in the choir?',
      answer: 'No', distractors: ['Yes', 'Sometimes', 'Only on weekdays'], diff: 'easy', cog: 3, time: 25,
      explanation: 'No choir member plays football. Jake plays football, so Jake cannot be in the choir.' },
    { premise: 'Every pupil who brought a coat wore it outside. Ryan did not wear a coat outside. What can we conclude about Ryan?',
      answer: 'Ryan did not bring a coat', distractors: ['Ryan brought a coat', 'Ryan stayed inside', 'Ryan lost his coat'], diff: 'medium', cog: 5, time: 35,
      explanation: 'If bringing a coat means wearing it outside, and Ryan did not wear one outside, he did not bring one.' },
    { premise: 'Some books are hardback. All hardback books have covers. Do all books have covers?',
      answer: 'We cannot conclude this', distractors: ['Yes', 'No', 'Only hardback ones'], diff: 'medium', cog: 5, time: 35,
      explanation: 'All hardback books have covers, but we only know some books are hardback. Other books might not have covers.' },
    { premise: 'Red is darker than yellow. Blue is darker than red. Green is lighter than blue but darker than red. Rank them darkest to lightest.',
      answer: 'Blue, green, red, yellow', distractors: ['Blue, red, green, yellow', 'Green, blue, red, yellow', 'Red, blue, green, yellow'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Blue is darkest, then green (darker than red but lighter than blue), then red, then yellow.' },
    { premise: 'All planets orbit a star. Earth is a planet. The Moon orbits Earth. Does the Moon orbit a star?',
      answer: 'Not directly, but Earth orbits the Sun', distractors: ['Yes, the Moon is a planet', 'No', 'The Moon is a star'], diff: 'hard', cog: 7, time: 45,
      explanation: 'The Moon orbits Earth, which orbits the Sun. The Moon does not directly orbit a star.' },
    { premise: 'All mammals are warm-blooded. A lizard is cold-blooded. What can we conclude about the lizard?',
      answer: 'The lizard is not a mammal', distractors: ['The lizard is a mammal', 'The lizard is a bird', 'Nothing'], diff: 'easy', cog: 3, time: 25,
      explanation: 'All mammals are warm-blooded. The lizard is cold-blooded, so it cannot be a mammal.' },
    { premise: 'Anna runs faster than Beth. Beth runs faster than Claire. Claire runs faster than Diana. Who is the second fastest?',
      answer: 'Beth', distractors: ['Anna', 'Claire', 'Diana'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Anna > Beth > Claire > Diana. Beth is second fastest.' },
    { premise: 'Every triangle has three angles. Every equilateral triangle has three equal angles. Shape X has three angles but they are not all equal. What can we say?',
      answer: 'Shape X is a triangle but not equilateral', distractors: ['Shape X is equilateral', 'Shape X is not a triangle', 'Shape X is a square'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Three angles means it is a triangle. Unequal angles mean it is not equilateral.' },
    { premise: 'All birds have feathers. Penguins are birds. Penguins cannot fly. Which statement is true?',
      answer: 'Penguins have feathers but cannot fly', distractors: ['Penguins can fly', 'Penguins do not have feathers', 'All birds can fly'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Penguins are birds so they have feathers. The fact that they cannot fly does not change this.' },
    { premise: 'No Olympic sport is played alone indoors. Chess is played alone indoors. Is chess an Olympic sport?',
      answer: 'No', distractors: ['Yes', 'Sometimes', 'Only in winter'], diff: 'medium', cog: 5, time: 35,
      explanation: 'No Olympic sport is played alone indoors. Chess is played alone indoors, so chess is not an Olympic sport.' },
    { premise: 'All fruit contains seeds. Strawberries are fruit. Potatoes are not fruit. Which statement must be true?',
      answer: 'Strawberries contain seeds', distractors: ['Potatoes contain seeds', 'Strawberries are not fruit', 'All vegetables have seeds'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Strawberries are fruit and all fruit contains seeds, so strawberries contain seeds.' },
    { premise: 'Mark scored higher than Nora. Nora scored higher than Owen. Owen scored higher than Priya. Priya scored 60. What is the minimum Mark could have scored?',
      answer: '63', distractors: ['61', '62', '64'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Priya = 60, Owen > 60 so min 61, Nora > 61 so min 62, Mark > 62 so min 63.' },
  ];
  const questions: GeneratedQuestion[] = [];

  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.premise,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.logical_deduction',
      trapTypes: ['logical_fallacy'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: item.explanation,
      qaStatus: 'approved',
      stemVariantId: `logical_deduction_${i}`,
      distractorStyleId: 'logical_fallacy',
    }));
  }
  return questions;
}

function generateConditionalReasoningQuestions(): GeneratedQuestion[] {
  const items: { premise: string; answer: string; distractors: string[]; diff: string; cog: number; time: number; explanation: string }[] = [
    { premise: 'If you study hard, you will pass the exam. Tom did not pass the exam. What can we conclude about Tom?',
      answer: 'Tom did not study hard', distractors: ['Tom studied hard', 'Tom was ill', 'The exam was too difficult'], diff: 'medium', cog: 5, time: 35,
      explanation: 'By contrapositive: if not pass then not study hard. Tom did not pass, so he did not study hard.' },
    { premise: 'If a number is divisible by 6, it is divisible by both 2 and 3. The number 18 is divisible by 6. What else must be true?',
      answer: '18 is divisible by 2 and 3', distractors: ['18 is divisible by 5', '18 is a prime number', '18 is divisible by 9'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Since 18 is divisible by 6, it must be divisible by both 2 and 3.' },
    { premise: 'All members of the chess club can play chess. Not all members of the chess club can play draughts. Which statement must be true?',
      answer: 'Some chess club members cannot play draughts', distractors: ['No chess club members can play draughts', 'All chess club members can play draughts', 'Chess and draughts are the same game'], diff: 'medium', cog: 5, time: 35,
      explanation: '"Not all" means at least one cannot, so some chess club members cannot play draughts.' },
    { premise: 'If an animal has feathers, it is a bird. A robin has feathers. A dog does not have feathers. Which conclusion is correct?',
      answer: 'A robin is a bird and a dog is not necessarily a bird', distractors: ['A dog is a bird', 'A robin is not a bird', 'All animals are birds'], diff: 'medium', cog: 5, time: 35,
      explanation: 'A robin has feathers so it is a bird. A dog does not have feathers, but we cannot say it is definitely not a bird from this alone (though we know it is not).' },
    { premise: 'Every child who ate the school dinner had pudding. Every child who had pudding had a drink. Amy ate the school dinner. What can we say about Amy?',
      answer: 'Amy had pudding and a drink', distractors: ['Amy only had pudding', 'Amy only had a drink', 'Amy had neither'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Amy ate dinner → had pudding → had a drink. So Amy had both pudding and a drink.' },
    { premise: 'If it snows, the school closes. If the school closes, children stay home. It snowed on Monday. What happened on Monday?',
      answer: 'The school closed and children stayed home', distractors: ['The school stayed open', 'Only some children stayed home', 'Children went to a different school'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Snow → school closes → children stay home. All three follow from the chain of conditions.' },
    { premise: 'All quadrilaterals have four sides. All squares are quadrilaterals. All rectangles are quadrilaterals. Which must be true?',
      answer: 'Squares and rectangles both have four sides', distractors: ['All quadrilaterals are squares', 'All rectangles are squares', 'Squares have more sides than rectangles'], diff: 'hard', cog: 6, time: 40,
      explanation: 'Both squares and rectangles are quadrilaterals, so both have four sides.' },
    { premise: 'No vegetarian eats meat. Some vegetarians eat fish. Tom is a vegetarian who eats fish. What do we know about Tom?',
      answer: 'Tom does not eat meat but does eat fish', distractors: ['Tom eats meat and fish', 'Tom eats neither meat nor fish', 'Tom is not a vegetarian'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Tom is vegetarian so he does not eat meat. He is one of the vegetarians who eat fish.' },
    { premise: 'If a shape has three sides, it is a triangle. If a shape has four sides, it is a quadrilateral. A pentagon has five sides. What is a pentagon?',
      answer: 'Neither a triangle nor a quadrilateral', distractors: ['A triangle', 'A quadrilateral', 'A rectangle'], diff: 'easy', cog: 3, time: 25,
      explanation: 'A pentagon has five sides, so it is not a triangle (3) or quadrilateral (4).' },
    { premise: 'All children wearing red are on Team A. All children wearing blue are on Team B. Lucy is wearing green. Which team is Lucy on?',
      answer: 'We cannot tell', distractors: ['Team A', 'Team B', 'Both teams'], diff: 'medium', cog: 5, time: 35,
      explanation: 'We only know about red and blue. Lucy wears green, so we cannot determine her team.' },
    { premise: 'If a plant gets water and sunlight, it grows. A plant got water but no sunlight. What happens?',
      answer: 'We cannot be sure it will grow', distractors: ['It will definitely grow', 'It will definitely not grow', 'It will grow slowly'], diff: 'medium', cog: 5, time: 35,
      explanation: 'The rule says water AND sunlight are needed. Without sunlight, we cannot be sure it will grow.' },
    { premise: 'Every pupil in the maths club scored above 80 in the test. Sophie scored 75. What can we conclude?',
      answer: 'Sophie is not in the maths club', distractors: ['Sophie is in the maths club', 'Sophie needs to retake the test', 'Sophie scored the lowest'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Every maths club member scored above 80. Sophie scored 75, so she is not in the maths club.' },
    { premise: 'All cars in the car park are either red or blue. There are 15 cars. 9 are red. How many are blue?',
      answer: '6', distractors: ['9', '15', '24'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Total cars = 15, red = 9, so blue = 15 − 9 = 6.' },
    { premise: 'Some teachers drive to school. All teachers who drive arrive before 8am. Mrs Jones arrived at 8:15. What can we conclude?',
      answer: 'Mrs Jones did not drive to school', distractors: ['Mrs Jones drove to school', 'Mrs Jones is not a teacher', 'Mrs Jones was late'], diff: 'hard', cog: 7, time: 45,
      explanation: 'All driving teachers arrive before 8am. Mrs Jones arrived at 8:15, so she did not drive.' },
    { premise: 'Every student who passed the exam received a certificate. Every student who received a certificate was invited to the ceremony. Ali passed the exam. What happened to Ali?',
      answer: 'Ali received a certificate and was invited to the ceremony', distractors: ['Ali only received a certificate', 'Ali was not invited', 'Ali did not pass'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Ali passed → received certificate → was invited. Both follow from the chain.' },
    { premise: 'If a pupil finishes early, they may read quietly. Sam finished early. What may Sam do?',
      answer: 'Read quietly', distractors: ['Leave the classroom', 'Start the next test', 'Talk to friends'], diff: 'easy', cog: 3, time: 25,
      explanation: 'The rule states early finishers may read quietly. Sam finished early, so Sam may read quietly.' },
    { premise: 'If it is a weekday and before 9am, the gate is locked. It is Tuesday at 8:30am. Is the gate locked?',
      answer: 'Yes', distractors: ['No', 'Only half locked', 'We cannot tell'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Tuesday is a weekday and 8:30am is before 9am, so both conditions are met and the gate is locked.' },
    { premise: 'All children who completed the sponsored walk raised at least £10. Ben completed the walk. What is the minimum Ben raised?',
      answer: '£10', distractors: ['£5', '£20', '£0'], diff: 'easy', cog: 3, time: 25,
      explanation: 'All completers raised at least £10. Ben completed the walk, so he raised at least £10.' },
    { premise: 'If a number is even, it ends in 0, 2, 4, 6 or 8. The number 357 ends in 7. What can we say?',
      answer: '357 is not even', distractors: ['357 is even', '357 ends in 0', '357 is prime'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Even numbers end in 0, 2, 4, 6 or 8. 357 ends in 7, so it is not even.' },
    { premise: 'All prefects must be in Year 6. All prefects must have a good attendance record. Zara is in Year 5. Can Zara be a prefect?',
      answer: 'No', distractors: ['Yes', 'Only with good attendance', 'Sometimes'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Prefects must be in Year 6. Zara is in Year 5, so she cannot be a prefect regardless of attendance.' },
    { premise: 'Every child who joins the nature club must attend at least 3 sessions a term. The nature club has 12 sessions a term. What is the maximum sessions a member could miss?',
      answer: '9', distractors: ['3', '12', '6'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Must attend at least 3 out of 12 sessions. Maximum missed = 12 − 3 = 9.' },
    { premise: 'If today is Thursday, tomorrow is Friday. If tomorrow is Friday, the school has assembly. Today is Thursday. What happens tomorrow?',
      answer: 'The school has assembly', distractors: ['Nothing special', 'Sports day', 'A holiday'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Today is Thursday → tomorrow is Friday → school has assembly. Chain of conditions gives the answer.' },
  ];

  const questions: GeneratedQuestion[] = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.premise,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.conditional_reasoning',
      trapTypes: ['affirming_consequent', 'chain_logic'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: item.explanation,
      qaStatus: 'approved',
      stemVariantId: `conditional_reasoning_${i}`,
      distractorStyleId: 'logical_fallacy',
    }));
  }
  return questions;
}

function generateTableDeductionQuestions(): GeneratedQuestion[] {
  const items: { premise: string; answer: string; distractors: string[]; diff: string; cog: number; time: number; explanation: string }[] = [
    { premise: 'Three children — Amy, Ben and Cara — each have a different pet: a cat, a dog and a rabbit. Amy does not have a cat. Ben has the dog. What pet does Amy have?',
      answer: 'A rabbit', distractors: ['A cat', 'A dog', 'A hamster'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Ben has the dog. Amy does not have a cat. So Amy has the rabbit, and Cara has the cat.' },
    { premise: 'Four friends — Dan, Eve, Fay and Gus — sit in a row. Dan sits at one end. Eve sits next to Dan. Fay does not sit next to Gus. Who sits at the other end?',
      answer: 'Gus', distractors: ['Eve', 'Fay', 'Dan'], diff: 'medium', cog: 6, time: 45,
      explanation: 'Dan is at one end, Eve next to Dan. The remaining seats go to Fay and Gus. If Fay is not next to Gus, Fay must be next to Eve, and Gus is at the other end.' },
    { premise: 'Three children — Isla, Jake and Kim — each like a different fruit: apples, bananas and cherries. Isla does not like bananas. Jake does not like apples or bananas. What does Kim like?',
      answer: 'Bananas', distractors: ['Apples', 'Cherries', 'Oranges'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Jake does not like apples or bananas, so Jake likes cherries. Isla does not like bananas, so Isla likes apples. Kim likes bananas.' },
    { premise: 'Leo, Mia and Noor each play a different instrument: piano, violin and flute. Leo does not play piano. Mia plays violin. What instrument does Leo play?',
      answer: 'Flute', distractors: ['Piano', 'Violin', 'Drums'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Mia plays violin. Leo does not play piano. So Leo plays flute and Noor plays piano.' },
    { premise: 'Five children sit in a row numbered 1 to 5. Alice sits in seat 1. Ben does not sit next to Alice. Charlie is between Dana and Eve. Dana sits in seat 2. Where does Ben sit?',
      answer: 'Seat 5', distractors: ['Seat 2', 'Seat 3', 'Seat 4'], diff: 'hard', cog: 8, time: 55,
      explanation: 'Alice=1, Dana=2. Charlie is between Dana and Eve, so Dana-Charlie-Eve gives seats 2-3-4. Ben cannot be next to Alice (seat 2), so Ben sits in seat 5.' },
    { premise: 'Four pupils — Priya, Quinn, Raj and Sara — each scored a different mark in a test: 60, 70, 80 and 90. Priya scored higher than Quinn. Raj scored 80. Sara scored the lowest. What did Quinn score?',
      answer: '70', distractors: ['60', '80', '90'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Sara scored the lowest = 60. Raj scored 80. Remaining scores are 70 and 90. Priya > Quinn, so Priya = 90 and Quinn = 70.' },
    { premise: 'Three teams — Red, Blue and Green — finished a relay race in 1st, 2nd and 3rd place. Red did not finish last. Blue finished before Green. In what position did Green finish?',
      answer: '3rd', distractors: ['1st', '2nd', 'Did not finish'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Blue finished before Green, so Green is not 1st. Red did not finish last. If Green is not 1st and someone else is not last, Green must be 3rd.' },
    { premise: 'Tom, Uma and Vic each wore a different colour hat: red, blue and yellow. Tom did not wear red or blue. Uma did not wear yellow. What colour hat did Uma wear?',
      answer: 'Red or blue', distractors: ['Yellow', 'Red only', 'Green'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Tom wore yellow (not red or blue). Uma did not wear yellow. So Uma wore either red or blue.' },
    { premise: 'Four children — Ava, Ben, Clara and Dan — each chose a different drink: water, milk, juice and tea. Ava did not choose water or milk. Ben chose tea. Clara did not choose juice. What did Dan choose?',
      answer: 'Water or milk', distractors: ['Juice', 'Tea', 'Water only'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Ben chose tea. Ava did not choose water or milk, so Ava chose juice. Clara did not choose juice (already taken). Remaining: water and milk for Clara and Dan.' },
    { premise: 'Three friends — Ella, Finn and Grace — each have a different hobby: painting, reading and singing. Ella does not paint. Finn sings. What is Ella\'s hobby?',
      answer: 'Reading', distractors: ['Painting', 'Singing', 'Dancing'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Finn sings. Ella does not paint. So Ella reads and Grace paints.' },
    { premise: 'Five pupils sit in numbered seats 1 to 5. Hana is in seat 2. Ian is not in seat 1 or seat 5. Jade is in seat 4. Kara is in seat 1. Where does Leo sit?',
      answer: 'Seat 5', distractors: ['Seat 3', 'Seat 1', 'Seat 4'], diff: 'medium', cog: 6, time: 45,
      explanation: 'Kara=1, Hana=2, Jade=4. Ian is not in 1 or 5, so Ian=3. Leo takes seat 5.' },
    { premise: 'Four children — Mo, Nina, Owen and Pat — finished a race. Mo was not first or last. Nina finished before Owen. Pat was last. In what position did Mo finish?',
      answer: '2nd or 3rd', distractors: ['1st', '4th', '2nd only'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Pat was last (4th). Mo was not first or last. Nina finished before Owen. So Mo is 2nd or 3rd.' },
    { premise: 'Three children each have a different favourite subject: maths, science and English. Quinn does not like maths. Rose likes science. What is Quinn\'s favourite subject?',
      answer: 'English', distractors: ['Maths', 'Science', 'History'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Rose likes science. Quinn does not like maths. So Quinn likes English.' },
    { premise: 'Three children — Sam, Tara and Uma — each have a different pet: a hamster, a goldfish and a rabbit. Sam has the goldfish. Tara does not have the rabbit. What pet does Uma have?',
      answer: 'A rabbit', distractors: ['A hamster', 'A goldfish', 'A cat'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Sam has the goldfish. Tara does not have the rabbit, so Tara has the hamster. Uma has the rabbit.' },
    { premise: 'Four children — Will, Xena, Yuri and Zara — each have a different favourite colour: red, blue, green and yellow. Will likes red. Xena does not like blue or yellow. Zara likes yellow. What colour does Yuri like?',
      answer: 'Blue', distractors: ['Red', 'Green', 'Yellow'], diff: 'medium', cog: 6, time: 45,
      explanation: 'Will=red, Zara=yellow. Xena does not like blue or yellow, so Xena=green. Yuri=blue.' },
    { premise: 'Three friends — Alice, Beth and Cara — each ordered a different meal: pizza, pasta and salad. Alice did not order pizza. Beth ordered salad. What did Alice order?',
      answer: 'Pasta', distractors: ['Pizza', 'Salad', 'Soup'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Beth ordered salad. Alice did not order pizza, so Alice ordered pasta. Cara ordered pizza.' },
    { premise: 'Four children sat at a round table. Dan sat opposite Eve. Finn sat to the left of Dan. Who sat to the right of Dan?',
      answer: 'The fourth child (not Eve or Finn)', distractors: ['Eve', 'Finn', 'Dan'], diff: 'medium', cog: 6, time: 45,
      explanation: 'Dan is opposite Eve. Finn is to Dan\'s left. The fourth child sits to Dan\'s right.' },
    { premise: 'Three pupils — Gina, Harry and Isla — each scored a different mark: 5, 7 and 9. Gina scored higher than Harry. Isla scored 7. What did Harry score?',
      answer: '5', distractors: ['7', '9', '6'], diff: 'easy', cog: 4, time: 30,
      explanation: 'Isla=7. Gina > Harry, with remaining scores 5 and 9. So Gina=9, Harry=5.' },
    { premise: 'Five children — Jo, Kay, Lee, Mo and Ned — stand in a line. Jo is first. Ned is last. Kay is between Lee and Mo. Lee is second. Where does Mo stand?',
      answer: '4th', distractors: ['2nd', '3rd', '5th'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Jo=1st, Lee=2nd, Ned=5th. Kay is between Lee and Mo. Lee=2nd, so Kay=3rd, Mo=4th.' },
    { premise: 'Three teams played a tournament. Team A beat Team B. Team B beat Team C. Team C did not beat Team A. Which team won the tournament?',
      answer: 'Team A', distractors: ['Team B', 'Team C', 'It was a draw'], diff: 'easy', cog: 4, time: 30,
      explanation: 'A beat B, B beat C, and C did not beat A. So Team A won all its matches.' },
  ];

  const questions: GeneratedQuestion[] = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.premise,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.table_deduction',
      trapTypes: ['elimination_error', 'constraint_miss'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: item.explanation,
      qaStatus: 'approved',
      stemVariantId: `table_deduction_${i}`,
      distractorStyleId: 'elimination_error',
    }));
  }
  return questions;
}

function generateSeatingArrangementQuestions(): GeneratedQuestion[] {
  const items: { premise: string; answer: string; distractors: string[]; diff: string; cog: number; time: number; explanation: string }[] = [
    { premise: 'Three children sit in a row: Ali, Beth and Cal. Ali sits on the left. Cal does not sit next to Ali. Who sits in the middle?',
      answer: 'Beth', distractors: ['Ali', 'Cal', 'Cannot be determined'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Ali is on the left. Cal is not next to Ali, so Cal is on the right. Beth is in the middle.' },
    { premise: 'Four children sit around a square table: Dan, Eve, Fay and Gus. Dan sits opposite Eve. Fay sits to the left of Dan. Who sits to the right of Dan?',
      answer: 'Gus', distractors: ['Eve', 'Fay', 'Dan'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Dan is opposite Eve. Fay is to Dan\'s left. The remaining seat (Dan\'s right) must be Gus.' },
    { premise: 'Five children sit in a row. Hannah is in the middle. Ian is not at either end. Jenny sits to the left of Hannah. Karl is at the right end. Where does Lily sit?',
      answer: 'At the left end', distractors: ['Next to Karl', 'In the middle', 'Second from the right'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Hannah is seat 3 (middle). Karl is seat 5 (right end). Jenny is to the left of Hannah, and Ian is not at either end. Ian must be seat 4, Jenny seat 2, Lily seat 1.' },
    { premise: 'Six pupils sit in a circle. Max is opposite Nina. Oscar is to the left of Max. Pip is opposite Oscar. Who is to the right of Nina?',
      answer: 'Oscar', distractors: ['Max', 'Pip', 'Cannot be determined'], diff: 'hard', cog: 8, time: 55,
      explanation: 'In a circle of 6, Max opposite Nina means 3 seats apart. Oscar to Max\'s left, Pip opposite Oscar. Working through the positions, Oscar ends up to Nina\'s right.' },
    { premise: 'Three friends sit on a bench. Ravi is not at either end. Sofia sits to the right of Ravi. Where does Tom sit?',
      answer: 'On the left end', distractors: ['In the middle', 'On the right end', 'Cannot be determined'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Ravi is in the middle. Sofia is to his right (right end). Tom must be on the left end.' },
    { premise: 'Four people sit in a row. Uma is next to Vic. Wen is at one end. Xia is not next to Wen. Who sits next to Wen?',
      answer: 'Uma or Vic', distractors: ['Xia', 'Nobody', 'Both Uma and Vic'], diff: 'hard', cog: 6, time: 45,
      explanation: 'Xia is not next to Wen. Uma is next to Vic. Since Xia cannot be next to Wen, either Uma or Vic must be next to Wen.' },
    { premise: 'Five children sit in seats numbered 1-5. Yara is in seat 3. Zain is in an even-numbered seat. Ava is in seat 1. Ben is not in seat 5. Where does Ben sit?',
      answer: 'Seat 2 or seat 4', distractors: ['Seat 1', 'Seat 3', 'Seat 5'], diff: 'hard', cog: 7, time: 50,
      explanation: 'Ava=1, Yara=3. Ben is not in seat 5. Zain is in an even seat. Ben must be in seat 2 or 4 (the remaining even seat goes to Zain).' },
    { premise: 'Four children sit in a row. Sam is on the left. Tara sits next to Sam. Umar is not next to Tara. Where does Vera sit?',
      answer: 'Next to Tara', distractors: ['On the right end', 'Next to Umar', 'Next to Sam'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Sam is left, Tara next to Sam (seat 2). Umar is not next to Tara, so Umar is seat 4. Vera is seat 3, next to Tara.' },
    { premise: 'Three children sit on a bench. Will is in the middle. Xena is to Will\'s left. Where does Yasmin sit?',
      answer: 'To Will\'s right', distractors: ['In the middle', 'To Will\'s left', 'Cannot be determined'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Will is in the middle, Xena on his left, so Yasmin is on his right.' },
    { premise: 'Six pupils sit in two rows of three facing each other. Amira sits opposite Boris. Cleo sits next to Amira. Dev sits opposite Cleo. Who sits opposite the person next to Boris?',
      answer: 'Amira or Cleo', distractors: ['Boris', 'Dev', 'Cannot be determined'], diff: 'hard', cog: 8, time: 55,
      explanation: 'Amira opposite Boris, Cleo next to Amira, Dev opposite Cleo. The person next to Boris sits opposite Amira or Cleo.' },
    { premise: 'Three pupils — Raj, Sara and Tom — sit in a row. Tom is not at either end. Sara sits to the left of Tom. Where does Raj sit?',
      answer: 'On the right end', distractors: ['On the left end', 'In the middle', 'Cannot be determined'], diff: 'easy', cog: 3, time: 25,
      explanation: 'Tom is in the middle. Sara is to Tom\'s left (left end). Raj is on the right end.' },
    { premise: 'Four friends sit in a row numbered 1-4. Anna is in seat 1. Charlie is in seat 3. Ben is not in seat 4. Where does Dana sit?',
      answer: 'Seat 4', distractors: ['Seat 2', 'Seat 1', 'Seat 3'], diff: 'medium', cog: 5, time: 40,
      explanation: 'Anna=1, Charlie=3. Ben is not in seat 4, so Ben=2. Dana=4.' },
    { premise: 'Five children sit in a circle. Ella is to the left of Frank. Grace is opposite Frank. Harry is to the right of Grace. Where is Ivy?',
      answer: 'Between Harry and Ella', distractors: ['Opposite Ella', 'Next to Frank', 'Between Frank and Grace'], diff: 'hard', cog: 8, time: 55,
      explanation: 'In a circle of 5, Frank has Ella to his left. Grace is opposite Frank. Harry is to Grace\'s right. Ivy fills the remaining position between Harry and Ella.' },
  ];

  const questions: GeneratedQuestion[] = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.premise,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.seating_arrangement',
      trapTypes: ['spatial_reasoning', 'constraint_miss'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: item.explanation,
      qaStatus: 'approved',
      stemVariantId: `seating_arrangement_${i}`,
      distractorStyleId: 'spatial_reasoning',
    }));
  }
  return questions;
}

function generateComplexSyllogismQuestions(): GeneratedQuestion[] {
  const items: { premise: string; answer: string; distractors: string[]; diff: string; cog: number; time: number; explanation: string }[] = [
    { premise: 'All athletes are fit. Some fit people are tall. Can we say all athletes are tall?',
      answer: 'No, we cannot conclude that', distractors: ['Yes, all athletes are tall', 'Only some athletes exist', 'Athletes are always tall'], diff: 'medium', cog: 5, time: 35,
      explanation: 'All athletes are fit, and some fit people are tall, but not all fit people are tall. So we cannot conclude all athletes are tall.' },
    { premise: 'No mammals can breathe underwater. Dolphins are mammals. Dolphins live in water. Which statement is correct?',
      answer: 'Dolphins must come to the surface to breathe', distractors: ['Dolphins can breathe underwater', 'Dolphins are not mammals', 'Dolphins do not live in water'], diff: 'medium', cog: 6, time: 40,
      explanation: 'Dolphins are mammals and no mammals can breathe underwater, so dolphins must surface to breathe, even though they live in water.' },
    { premise: 'All prefects are in Year 6. Some Year 6 pupils play football. All football players train on Wednesday. What can we say about some prefects?',
      answer: 'We cannot say anything definite about prefects and football', distractors: ['All prefects train on Wednesday', 'No prefects play football', 'All prefects play football'], diff: 'hard', cog: 8, time: 50,
      explanation: 'All prefects are in Year 6, and some Year 6 pupils play football, but we do not know if any prefects are among those who play football.' },
    { premise: 'Every doctor has studied science. Every surgeon is a doctor. Not every doctor is a surgeon. What must be true?',
      answer: 'Every surgeon has studied science', distractors: ['Every scientist is a doctor', 'Every doctor is a surgeon', 'No doctors study science'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Every surgeon is a doctor, and every doctor has studied science. So every surgeon has studied science.' },
    { premise: 'Some sweets are chocolate. All chocolate is brown. Some brown things are round. Are some sweets definitely brown?',
      answer: 'Some sweets are brown', distractors: ['All sweets are brown', 'No sweets are brown', 'All sweets are round'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Some sweets are chocolate, and all chocolate is brown. So those sweets that are chocolate must be brown. Therefore some sweets are brown.' },
    { premise: 'All pentagons have five sides. All shapes on the board are pentagons. Shape X is on the board. How many sides does Shape X have?',
      answer: 'Five', distractors: ['Four', 'Six', 'Three'], diff: 'medium', cog: 4, time: 30,
      explanation: 'Shape X is on the board, all shapes on the board are pentagons, and all pentagons have five sides. So Shape X has five sides.' },
    { premise: 'No birds are reptiles. All crocodiles are reptiles. Some animals that live near water are birds. Can a crocodile be a bird?',
      answer: 'No', distractors: ['Yes', 'Sometimes', 'Only near water'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Crocodiles are reptiles and no birds are reptiles, so a crocodile cannot be a bird.' },
    { premise: 'All coins in the red box are gold. All coins in the blue box are silver. No coin is in both boxes. A coin is gold. Where could it be?',
      answer: 'In the red box or somewhere else entirely', distractors: ['Definitely in the red box', 'In the blue box', 'In both boxes'], diff: 'hard', cog: 8, time: 50,
      explanation: 'All coins in the red box are gold, but there could be gold coins elsewhere too. So a gold coin could be in the red box or elsewhere.' },
    { premise: 'All Year 6 pupils study French. Some pupils who study French also study Spanish. Tom is in Year 6. Does Tom study Spanish?',
      answer: 'We cannot be sure', distractors: ['Yes', 'No', 'Only on Tuesdays'], diff: 'medium', cog: 5, time: 35,
      explanation: 'Tom studies French (he is in Year 6), but only some French students also study Spanish. We cannot be certain.' },
    { premise: 'No reptiles have fur. All mammals have fur. A platypus has fur and lays eggs. What must be true?',
      answer: 'A platypus is a mammal, not a reptile', distractors: ['A platypus is a reptile', 'A platypus is a bird', 'A platypus has no fur'], diff: 'hard', cog: 7, time: 45,
      explanation: 'The platypus has fur, so it is a mammal. No reptiles have fur, so it is not a reptile.' },
    { premise: 'Every child who practises an instrument improves. Some children who improve join the orchestra. Beth practises the violin. Will Beth join the orchestra?',
      answer: 'She might but we cannot be certain', distractors: ['Yes, definitely', 'No, never', 'Only if she is in Year 6'], diff: 'hard', cog: 7, time: 45,
      explanation: 'Beth practises so she will improve. But only some children who improve join the orchestra, so it is not certain.' },
    { premise: 'All squares have equal sides. All rhombuses have equal sides. Does that mean all rhombuses are squares?',
      answer: 'No, having equal sides does not make a shape a square', distractors: ['Yes', 'Sometimes', 'Only if they have right angles'], diff: 'medium', cog: 6, time: 40,
      explanation: 'Both have equal sides, but squares also need right angles. Having equal sides alone does not make a rhombus a square.' },
    { premise: 'All children in the school wear a uniform. A child is wearing a uniform. Is the child from this school?',
      answer: 'Not necessarily', distractors: ['Yes', 'No', 'Only during term time'], diff: 'medium', cog: 5, time: 35,
      explanation: 'All children at the school wear a uniform, but other schools may have uniforms too. We cannot be sure.' },
  ];

  const questions: GeneratedQuestion[] = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const options = shuffle([item.answer, ...item.distractors]);
    questions.push(makeQ({
      type: 'verbal_logic',
      prompt: item.premise,
      options,
      correctAnswer: item.answer,
      difficulty: item.diff,
      skillId: 'vr.verbal_logic',
      subRuleId: 'vr.verbal_logic.complex_syllogism',
      trapTypes: ['syllogism_reversal', 'distribution_error'],
      cognitiveLoad: item.cog,
      estTimeSeconds: item.time,
      explanation: item.explanation,
      qaStatus: 'approved',
      stemVariantId: `complex_syllogism_${i}`,
      distractorStyleId: 'syllogism_reversal',
    }));
  }
  return questions;
}

export function generateVerbalLogicQuestions(): GeneratedQuestion[] {
  return [
    ...generateSentenceCompletionQuestions(),
    ...generateLogicalDeductionQuestions(),
    ...generateConditionalReasoningQuestions(),
    ...generateTableDeductionQuestions(),
    ...generateSeatingArrangementQuestions(),
    ...generateComplexSyllogismQuestions(),
  ];
}
